spring.application.name=portfolio

spring.datasource.username=root
spring.datasource.password= pawan131208
spring.datasource.url=jdbc:mysql://localhost:3306/portfolio

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
